---
title: Teaching
---

In addition to my research, I also enjoy teaching and mentoring. I have I taught an upper-level psychology class in Fall 2025 (~30 students) about my favorite subject—Language and Thought. This course covered fun topics such as language development, linguistic relativity, language and technology, bilingualism, and more! I am currently preparing to teach PSYCH 100 this fall (~350 students).

One of the many privileges of teaching psychology is that course content inherently and directly relates to individuals’ own experiences! As psychologists, and in psychology classes, we discuss questions that are fundamental to the human experience. My primary goal as an instructor is to foster a love of learning and sense of curiosity in my students. I aim to create classroom environments where students can develop a positive relationship with the learning process and learn to ask reflective and critical questions driven by their own interests and curiosity.

<!-- Below are links to various in-class activities and assignments I have created, as well as links to activities or demonstrations I have found particularly useful. If you know of any resources or activities that help students develop critical thinking skills, make material more engaging, or encourage students to relate material to their own lives, please reach out and send them my way! -->

## Teaching Research

Recently, I have begun to combine my interests in teaching and research. In collaboration with Teaching Professor Dr. Alicia Drais-Parrillo at Penn State, I have helped analyze data from a large-scale project on content-retention in psychology classes. This work has resulted in a conference talk at the Scholarship of Teaching and Learning Summit on the role of grades, interest, and study time on undergraduate psychology content-retention. 

## Mentorship
I am lucky to get to work with dozens of amazing undergraduate research assistants in the BiLD Lab. I have enjoyed getting to work closely with students who are invested in our ongoing research projects, such as two students who are currently trained to independently run the behavioral session of my dissertation experiment. I have also enjoyed mentoring students through the completion of their own research projects, from idea development to data analysis. I have mentored four students who developed their own research studies and conducted the research abroad independently (three in the Netherlands and one in Spain). Upon their return to the States after data collection, I mentored students through data analysis, and presenting their work at the undergraduate research fair. I especially enjoyed working with one of these students, who was highly motivated to pursue research, and additionally mentored her as she completed an undergraduate honors thesis using this research data, and is a co-author on one of my submitted manuscripts. 
